version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: my_neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4JLABS_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./docker/neo4j/data:/data
      - ./docker/neo4j/logs:/logs
      - ./docker/neo4j/import:/var/lib/neo4j/import
      - ./docker/neo4j/plugins:/plugins

    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  backend:
    build:
      context: wallet-branch-blockchain 
      dockerfile: Dockerfile
    container_name: go_backend
    ports:
      - "8080:8080"
    environment:
      NEO4J_URI: neo4j://neo4j:7687
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      BLOCKCHAIN_URL: ${BLOCKCHAIN_URL}
    depends_on:
      neo4j:
        condition: service_healthy

  frontend:
    build: ./wallet-searcher
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend